### ISSUE TITLE
config files with a lot of entries

### ISSUE THREAD

**Issue by daveism** [SouthFACT/landsatfact-data#118]
a lot of entries in this file
- ./project/html/landsatfact_config.xml
- ./project/msconfig/makeviewerconfig.py
- ./project/msconfig/landsatfact_config.tpl.xml

.map fles
- ./project/msconfig/vlayers.map
- ./project/msconfig/lsf-cr-swir-allchange.map
- ./project/msconfig/lsf-cr-swir-threshold.map
- ./project/msconfig/lsf-swir-allchange.map
- ./project/msconfig/lsf-swir-threshold.map
- ./project/msconfig/lsf-cr-ndvi.map
- ./project/msconfig/lsf-ndvi.map
- ./project/msconfig/lsf-ndmi.map
- ./project/msconfig/lsf-cr-ndmi.map
- /project/msconfig/rlayers.tpl.map

**Comment by daveism** [comment]
@mwhutchi  should these map files and viewer config files reference paths as a variable?

**Comment by mwhutchi** [comment]
These .map files get generated by a script that already contains path variables, so these can be left alone.
