### ISSUE TITLE
Setup Cronjob and verify permissions on all resulting files are correct

### ISSUE THREAD

**Issue by mwhutchi** [SouthFACT/landsatfact-data#19]
Setup and test the [Cronjob](http://en.wikipedia.org/wiki/Cron) for downloading the TARs to look at server load and transactional "costs" for getting the imagery downloaded

**Comment by geoderek** [comment]
For now I think it makes sense to schedule the following two scripts in order:

| Order | Directory | Script |
| --- | :-: | --: |
| 1 | dataexchange | update_landsat_metadata.php |
| 2 | dataexchange | download_landsat_data.php |
| 3 | geoprocessing | landsatFACTmain.py |

**Comment by mwhutchi** [comment]
Should the other geoprocessing/mapfile scripts stand alone or does it make sense to incorporate them into one or multiple scripts? There could even be a bash script that runs them. The ones I'm thinking about include:
- mosaic_products.py (creates a southeast latest change mosaic for each product)
- makemap.py (creates the MapServer mapfiles)
- makeviewerconfig.py (creates the Viewer config file)

**Comment by geoderek** [comment]
I am thinking to keep them separate with each having a specific purpose as you have listed them.  The cronjob itself runs a bash script which we can add these script to potentially.

**Comment by geoderek** [comment]
Need to adjust the permissions of the resulting tar files that are downloaded accordingly because they are not coming down with group writable.

**Comment by geoderek** [comment]
Still some issue w/ permissions on the Linux going on here.  I think it has to do w/ sticky bits but can't be sure until I research it more.  I know that if I run the geoprocessing scripts as sudo things complete through.  Also, when I check the permissions after the cronjob runs or I run as myself often the group right is removed.

**Comment by mwhutchi** [comment]
The cron job is working and permission issues have been fixed.
