### ISSUE TITLE
Raster product directory

### ISSUE THREAD

**Issue by mwhutchi** [SouthFACT/landsatfact-data#21]
Create raster folder directory structure

**Comment by mwhutchi** [comment]
| Desc | Path |
| --- | :-: |
| Downloaded tar files from USGS EROS | fsdata1/lsfdata/tarFiles |
| Extracted tar files | fsdata1/lsfdata/tarFiles/extractedTars |
| Raw imagery | fsdata1/lsfdata/raw_imagery |
| Product directory | fsdata1/lsfdata/products |
| NDVI products | fsdata1/lsfdata/products/ndvi |
| NDMI products | fsdata1/lsfdata/products/ndmi |
| B7Diff products | fsdata1/lsfdata/products/b7diff |
| Gap mask products | fsdata1/lsfdata/products/gap_mask |
| Cloud mask products | fsdata1/lsfdata/products/cloud_mask |
| Raster mosaics that get updated each day by gdalwarp | fsdata1/lsfdata/products/mosaics |

**Comment by geoderek** [comment]
I think this is done.  I have added these directories to the geoprocessing script accordingly.
