### ISSUE TITLE
Add projection to wrs2_codes table for Index to pull from

### ISSUE THREAD

**Issue by geoderek** [SouthFACT/landsatfact-data#37]
This would then be used to update the wrs2_codes table so that the product tile index can pull in the specific UTM zone projection information... should be a one-time thing

**Comment by geoderek** [comment]
Using script to get the wrs2_code by proj4 string into csv and then import/join to wrs2_codes table

**Comment by mwhutchi** [comment]
This was done and is working for all archive products.
